// users actions
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_SLIDES = 'GET_SLIDES';
export const GET_SLIDES_SUCCESS = 'GET_SLIDES_SUCCESS';
export const GET_SLIDES_ERROR = 'GET_SLIDES_ERROR';
export const ACTIVE_SLIDE = 'ACTIVE_SLIDE';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GET_LOGIN_USER = 'GET_LOGIN_USER';
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const SAVE_PERSONAL_DATA_ERROR = 'SAVE_PERSONAL_DATA_ERROR';
export const SAVE_PERSONAL_DATA_REQUEST = 'SAVE_PERSONAL_DATA_REQUEST';
export const SAVE_PERSONAL_DATA_SUCCESS = 'SAVE_PERSONAL_DATA_SUCCESS';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';


//swf actions
export const GET_SWF = 'GET_SWF';
export const GET_SWF_ERROR = 'GET_SWF_ERROR';
export const SET_SWF = 'SET_SWF';
export const SET_SWF_ERROR = 'SET_SWF_ERROR';
export const UPDATE_SWF_FIELDS = 'UPDATE_SWF_FIELDS';
export const UPDATE_SWF_FIELDS_ERROR = 'UPDATE_SWF_FIELDS_ERROR';
export const SWF_HAS_IMAGE = 'SWF_HAS_IMAGE';
export const SWF_RESET_IMAGE = 'SWF_RESET_IMAGE';
export const SWF_HAS_VIDEO = 'SWF_HAS_VIDEO';
export const SWF_RESET_VIDEO = 'SWF_RESET_VIDEO';

//slides actions
export const SAVE_SLIDE_SUCCESS = 'SAVE_SLIDE_SUCCESS';
export const UPDATE_ACTIVE_SLIDE = 'UPDATE_ACTIVE_SLIDE';
export const FILTER_SLIDES = 'FILTER_SLIDES';
export const SAVE_SLIDE_ERROR = 'SAVE_SLIDE_ERROR';
export const SAVE_SLIDE_REQUEST = 'SAVE_SLIDE_REQUEST';
export const SHOW_PUBLISHED_POPUP = 'SHOW_PUBLISHED_POPUP';
export const HIDE_PUBLISHED_POPUP = 'HIDE_PUBLISHED_POPUP';
export const UPDATE_ACTIVE_COMPOSITION = 'UPDATE_ACTIVE_COMPOSITION';
export const UPLOAD_IMAGE_MESSAGE_SUCCESS = 'UPLOAD_IMAGE_MESSAGE_SUCCESS';
export const UPLOAD_IMAGE_MESSAGE_ERROR = 'UPLOAD_IMAGE_MESSAGE_ERROR';
export const UPLOAD_IMAGE_MESSAGE_REQUEST = 'UPLOAD_IMAGE_MESSAGE_REQUEST';
export const ADD_NEW_SLIDE_SUCCESS = 'ADD_NEW_SLIDE_SUCCESS';
export const ADD_NEW_SLIDE_ERROR = 'ADD_NEW_SLIDE_ERROR';
export const ADD_NEW_SLIDE_REQUEST = 'ADD_NEW_SLIDE_REQUEST';
export const CANCEL_SLIDE_CHANGE = 'CANCEL_SLIDE_CHANGE';
export const DELETE_SLIDE_SUCCESS = 'DELETE_SLIDE_SUCCESS';
export const DELETE_SLIDE_ERROR = 'DELETE_SLIDE_ERROR';
export const DELETE_SLIDE_REQUEST = 'DELETE_SLIDE_REQUEST';
export const PUBLISHED_SLIDE_MESSAGE_SUBMITTING = 'PUBLISHED_SLIDE_MESSAGE_SUBMITTING';
export const UPDATE_SLIDE = 'UPDATE_SLIDE';

//slide video actions
export const UPLOAD_VIDEO_MESSAGE_START = 'UPLOAD_VIDEO_MESSAGE_START';
export const UPLOAD_VIDEO_MESSAGE_END = 'UPLOAD_VIDEO_MESSAGE_END';
export const UPLOAD_VIDEO_MESSAGE_CANCEL = 'UPLOAD_VIDEO_MESSAGE_CANCEL';
export const SET_UPLOAD_VIDEO_MESSAGE_PERCENT = 'SET_UPLOAD_VIDEO_MESSAGE_PERCENT';
export const UPLOAD_VIDEO_MESSAGE_SUCCESS = 'UPLOAD_VIDEO_MESSAGE_SUCCESS';
export const UPLOAD_VIDEO_MESSAGE_ERROR = 'UPLOAD_VIDEO_MESSAGE_ERROR';
export const UPLOAD_VIDEO_MESSAGE_REQUEST = 'UPLOAD_VIDEO_MESSAGE_REQUEST';
export const UPLOAD_VIDEO_MESSAGE_DELETE = 'UPLOAD_VIDEO_MESSAGE_DELETE';
export const UPLOAD_VIDEO_MESSAGE_NAME = 'UPLOAD_VIDEO_MESSAGE_NAME';

//encoding slide video
export const ENCODING_VIDEO_SUCCESS = 'ENCODING_VIDEO_SUCCESS';
export const ENCODING_VIDEO_ERROR = 'ENCODING_VIDEO_ERROR';
export const ENCODING_VIDEO_REQUEST = 'ENCODING_VIDEO_REQUEST';

//update message data
export const GET_MESSAGE_BY_ID_SUCCESS = 'GET_MESSAGE_BY_ID_SUCCESS';
export const GET_MESSAGE_BY_ID_ERROR = 'GET_MESSAGE_BY_ID_ERROR';
export const GET_MESSAGE_BY_ID_REQUEST = 'GET_MESSAGE_BY_ID_REQUEST';
export const UPDATE_MESSAGE_DATA_SUCCESS = 'UPDATE_MESSAGE_DATA_SUCCESS';
export const UPDATE_MESSAGE_DATA_ERROR = 'UPDATE_MESSAGE_DATA_ERROR';
export const UPDATE_MESSAGE_DATA_REQUEST = 'UPDATE_MESSAGE_DATA_REQUEST';
export const UPDATE_MESSAGE_RAW_ATTACHMENT_SUCCESS = 'UPDATE_MESSAGE_RAW_ATTACHMENT_SUCCESS';
export const UPDATE_MESSAGE_RAW_ATTACHMENT_ERROR = 'UPDATE_MESSAGE_RAW_ATTACHMENT_ERROR';
export const UPDATE_MESSAGE_RAW_ATTACHMENT_REQUEST = 'UPDATE_MESSAGE_RAW_ATTACHMENT_REQUEST';

//authors actions
export const GET_AUTHORS = 'GET_AUTHORS';
export const GET_AUTHORS_SUCCESS = 'GET_AUTHORS_SUCCESS';
export const GET_AUTHORS_ERROR = 'GET_AUTHORS_ERROR';

//authors categories
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

//user categories
export const GET_USER_CATEGORIES = 'GET_USER_CATEGORIES';
export const GET_USER_CATEGORIES_SUCCESS = 'GET_USER_CATEGORIES_SUCCESS';
export const GET_USER_CATEGORIES_ERROR = 'GET_USER_CATEGORIES_ERROR';
export const CREATE_USER_CATEGORY = 'CREATE_USER_CATEGORY';
export const CREATE_USER_CATEGORY_SUCCESS = 'CREATE_USER_CATEGORY_SUCCESS';
export const CREATE_USER_CATEGORY_ERROR = 'CREATE_USER_CATEGORY_ERROR';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

//user players
export const GET_USER_PLAYERS = 'GET_USER_PLAYERS';
export const GET_USER_PLAYERS_SUCCESS = 'GET_USER_PLAYERS_SUCCESS';
export const GET_USER_PLAYERS_ERROR = 'GET_USER_PLAYERS_ERROR';
export const SELECT_PLAYER = 'SELECT_PLAYER';
export const SELECT_ALL_PLAYERS = 'SELECT_ALL_PLAYERS';
export const PLAYERS_SELECTED = 'PLAYERS_SELECTED';

//tag types
export const GET_TAG_TYPES = 'GET_TAG_TYPES';
export const GET_TAG_TYPES_SUCCESS = 'GET_TAG_TYPES_SUCCESS';
export const GET_TAG_TYPES_ERROR = 'GET_TAG_TYPES_ERROR';

//tag by type
export const GET_TAG = 'GET_TAG';
export const GET_TAG_SUCCESS = 'GET_TAG_SUCCESS';
export const GET_TAG_ERROR = 'GET_TAG_ERROR';
export const SELECT_TAG = 'SELECT_TAG';
export const SELECTED_TAGS = 'SELECTED_TAGS';

//archive message
export const GET_ARCHIVE_MESSAGES_REQUEST = 'GET_ARCHIVE_MESSAGES_REQUEST';
export const GET_ARCHIVE_MESSAGES_SUCCESS = 'GET_ARCHIVE_MESSAGES_SUCCESS';
export const GET_ARCHIVE_MESSAGES_ERROR = 'GET_ARCHIVE_MESSAGES_ERROR';
export const FILTER_ARCHIVE_MESSAGE = 'FILTER_ARCHIVE_MESSAGE';
export const SELECT_ARCHIVE_MESSAGE = 'SELECT_ARCHIVE_MESSAGE';
export const DELETE_ARCHIVE_MESSAGE_SUCCESS = 'DELETE_ARCHIVE_MESSAGE_SUCCESS';
export const DELETE_ARCHIVE_MESSAGE_ERROR = 'DELETE_ARCHIVE_MESSAGE_ERROR';
export const DELETE_ARCHIVE_MESSAGE_REQUEST = 'DELETE_ARCHIVE_MESSAGE_REQUEST';
export const CHECKED_ARCHIVE_MESSAGE = 'CHECKED_ARCHIVE_MESSAGE';
export const CHECKED_ALL_ARCHIVE_MESSAGES = 'CHECKED_ALL_ARCHIVE_MESSAGES';
export const RETRIEVE_ARCHIVE_MESSAGE_SUCCESS = 'RETRIEVE_ARCHIVE_MESSAGE_SUCCESS';
export const RETRIEVE_ARCHIVE_MESSAGE_ERROR = 'RETRIEVE_ARCHIVE_MESSAGE_ERROR';
export const RETRIEVE_ARCHIVE_MESSAGE_REQUEST = 'RETRIEVE_ARCHIVE_MESSAGE_REQUEST';


//system status page
export const GET_SYSTEM_STATUS_PLAYERS_REQUEST = 'GET_SYSTEM_STATUS_PLAYERS_REQUEST';
export const GET_SYSTEM_STATUS_PLAYERS_SUCCESS = 'GET_SYSTEM_STATUS_PLAYERS_SUCCESS';
export const GET_SYSTEM_STATUS_PLAYERS_ERROR = 'GET_SYSTEM_STATUS_PLAYERS_ERROR';
export const FILTER_SYSTEM_STATUS_PLAYERS = 'FILTER_SYSTEM_STATUS_PLAYERS';


//player preview page
export const GET_PLAYER_PREVIEW_REQUEST = 'GET_PLAYERS_PREVIEW_REQUEST';
export const GET_PLAYER_PREVIEW_SUCCESS = 'GET_PLAYER_PREVIEW_SUCCESS';
export const GET_PLAYER_PREVIEW_ERROR = 'GET_PLAYER_PREVIEW_ERROR';
export const SELECT_PLAYER_PREVIEW = 'SELECT_PLAYER_PREVIEW';
export const SELECT_NEXT_PLAYER_PREVIEW = 'SELECT_NEXT_PLAYER_PREVIEW';
export const SELECT_PREVIEW_PLAYER_PREVIEW = 'SELECT_PREVIEW_PLAYER_PREVIEW';


//mobile page
export const GET_MOBILE_MESSAGES_REQUEST = 'GET_MOBILE_MESSAGES_REQUEST';
export const GET_MOBILE_MESSAGES_SUCCESS = 'GET_MOBILE_MESSAGES_SUCCESS';
export const GET_MOBILE_MESSAGES_ERROR = 'GET_MOBILE_MESSAGES_ERROR';
export const FILTER_MOBILE_MESSAGES = 'FILTER_MOBILE_MESSAGES';
export const SELECT_MOBILE_MESSAGE = 'SELECT_MOBILE_MESSAGE';
export const DELETE_MOBILE_MESSAGES_SUCCESS = 'DELETE_MOBILE_MESSAGES_SUCCESS';
export const DELETE_MOBILE_MESSAGES_ERROR = 'DELETE_MOBILE_MESSAGES_ERROR';
export const DELETE_MOBILE_MESSAGES_REQUEST = 'DELETE_MOBILE_MESSAGES_REQUEST';
export const SAVE_MOBILE_MESSAGES_SUCCESS = 'SAVE_MOBILE_MESSAGES_SUCCESS';
export const SAVE_MOBILE_MESSAGES_ERROR = 'SAVE_MOBILE_MESSAGES_ERROR';
export const SAVE_MOBILE_MESSAGES_REQUEST = 'SAVE_MOBILE_MESSAGES_REQUEST';
export const START_UPLOAD_MOBILE_MESSAGE_VIDEO = 'START_UPLOAD_MOBILE_MESSAGE_VIDEO';
export const END_UPLOAD_MOBILE_MESSAGE_VIDEO = 'END_UPLOAD_MOBILE_MESSAGE_VIDEO';
export const CANCEL_UPLOAD_MOBILE_MESSAGE_VIDEO = 'CANCEL_UPLOAD_MOBILE_MESSAGE_VIDEO';
export const SET_UPLOAD_MOBILE_MESSAGE_VIDEO_PERCENT = 'SET_UPLOAD_MOBILE_MESSAGE_VIDEO_PERCENT';
export const UPLOAD_MOBILE_MESSAGE_VIDEO_SUCCESS = 'UPLOAD_MOBILE_MESSAGE_VIDEO_SUCCESS';
export const UPLOAD_MOBILE_MESSAGE_VIDEO_ERROR = 'UPLOAD_MOBILE_MESSAGE_VIDEO_ERROR';
export const UPLOAD_MOBILE_MESSAGE_VIDEO_REQUEST = 'UPLOAD_MOBILE_MESSAGE_VIDEO_REQUEST';
export const UPLOAD_MOBILE_MESSAGE_IMAGE_SUCCESS = 'UPLOAD_MOBILE_MESSAGE_IMAGE_SUCCESS';
export const UPLOAD_MOBILE_MESSAGE_IMAGE_REQUEST = 'UPLOAD_MOBILE_MESSAGE_IMAGE_REQUEST';
export const UPLOAD_MOBILE_MESSAGE_IMAGE_ERROR = 'UPLOAD_MOBILE_MESSAGE_IMAGE_ERROR';
export const ENCODING_MOBILE_MESSAGE_VIDEO_SUCCESS = 'ENCODING_MOBILE_MESSAGE_VIDEO_SUCCESS';
export const ENCODING_MOBILE_MESSAGE_VIDEO_ERROR = 'ENCODING_MOBILE_MESSAGE_VIDEO_ERROR';
export const ENCODING_MOBILE_MESSAGE_VIDEO_REQUEST = 'ENCODING_MOBILE_MESSAGE_VIDEO_REQUEST';
export const UPDATE_MOBILE_MESSAGE_RAW_ATTACHMENT_SUCCESS = 'UPDATE_MOBILE_MESSAGE_RAW_ATTACHMENT_SUCCESS';
export const UPDATE_MOBILE_MESSAGE_RAW_ATTACHMENT_REQUEST = 'UPDATE_MOBILE_MESSAGE_RAW_ATTACHMENT_REQUEST';
export const UPDATE_MOBILE_MESSAGE_RAW_ATTACHMENT_ERROR = 'UPDATE_MOBILE_MESSAGE_RAW_ATTACHMENT_ERROR';
export const GET_MOBILE_MESSAGE_BY_ID_SUCCESS = 'GET_MOBILE_MESSAGE_BY_ID_SUCCESS';
export const GET_MOBILE_MESSAGE_BY_ID_REQUEST = 'GET_MOBILE_MESSAGE_BY_ID_REQUEST';
export const GET_MOBILE_MESSAGE_BY_ID_ERROR = 'GET_MOBILE_MESSAGE_BY_ID_ERROR';
export const UPDATE_MOBILE_MESSAGE_SUCCESS = 'UPDATE_MOBILE_MESSAGE_SUCCESS';
export const UPDATE_MOBILE_MESSAGE_ERROR = 'UPDATE_MOBILE_MESSAGE_ERROR';
export const GET_MOBILE_MESSAGE_USERS_REQUEST = 'GET_MOBILE_MESSAGE_USERS_REQUEST';
export const GET_MOBILE_MESSAGE_USERS_SUCCESS = 'GET_MOBILE_MESSAGE_USERS_SUCCESS';
export const GET_MOBILE_MESSAGE_USERS_ERROR = 'GET_MOBILE_MESSAGE_USERS_ERROR';
export const MOBILE_HIDE_PUBLISHED_POPUP = 'MOBILE_HIDE_PUBLISHED_POPUP';
export const MOBILE_SHOW_PUBLISHED_POPUP = 'MOBILE_SHOW_PUBLISHED_POPUP';
export const PUBLISHED_MOBILE_MESSAGE_SUBMITTING = 'PUBLISHED_MOBILE_MESSAGE_SUBMITTING';


//playlists page
export const GET_CONTENT_GROUPS = 'GET_CONTENT_GROUPS';
export const GET_CONTENT_GROUPS_SUCCESS = 'GET_CONTENT_GROUPS_SUCCESS';
export const GET_CONTENT_GROUPS_ERROR = 'GET_CONTENT_GROUPS_ERROR';
export const GET_PLAYLISTS = 'GET_PLAYLISTS';
export const GET_PLAYLISTS_SUCCESS = 'GET_PLAYLISTS_SUCCESS';
export const GET_PLAYLISTS_ERROR = 'GET_PLAYLISTS_ERROR';
export const GET_CHANNELS = 'GET_CHANNELS';
export const GET_CHANNELS_SUCCESS = 'GET_CHANNELS_SUCCESS';
export const GET_CHANNELS_ERROR = 'GET_CHANNELS_ERROR';
export const ADD_CONTENT_ITEM = 'ADD_CONTENT_ITEM';
export const REMOVE_CONTENT_ITEM = 'REMOVE_CONTENT_ITEM';
export const CONTENT_ITEM_POSITION = 'CONTENT_ITEM_POSITION';
export const SAVE_PLAYLIST_SUCCESS = 'SAVE_PLAYLIST_SUCCESS';
export const SAVE_PLAYLIST_ERROR = 'SAVE_PLAYLIST_ERROR';
export const SAVE_PLAYLIST = 'SAVE_PLAYLIST';
export const GET_ACTIVE_PLAYLIST_SUCCESS = 'GET_ACTIVE_PLAYLIST_SUCCESS';
export const GET_ACTIVE_PLAYLIST_ERROR = 'GET_ACTIVE_PLAYLIST_ERROR';
export const GET_ACTIVE_PLAYLIST = 'GET_ACTIVE_PLAYLIST';
export const PLAYLIST_SHOW_SAVED_POPUP = 'PLAYLIST_SHOW_SAVED_POPUP';
export const DISCARD_PLAYLIST = 'DISCARD_PLAYLIST';


// settings pages
export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const GET_USER_TYPES = 'GET_USER_TYPES';
export const GET_USER_TYPES_SUCCESS = 'GET_USER_TYPES_SUCCESS';
export const GET_USER_TYPES_ERROR = 'GET_USER_TYPES_ERROR';
export const GET_USER_RIGHTS = 'GET_USER_RIGHTS';
export const GET_USER_RIGHTS_SUCCESS = 'GET_USER_RIGHTS_SUCCESS';
export const GET_USER_RIGHTS_ERROR = 'GET_USER_RIGHTS_ERROR';
export const GET_USER_GROUPS = 'GET_USER_GROUPS';
export const GET_USER_GROUPS_SUCCESS = 'GET_USER_GROUPS_SUCCESS';
export const GET_USER_GROUPS_ERROR = 'GET_USER_GROUPS_ERROR';
export const SAVE_USER_GROUP_SUCCESS = 'SAVE_USER_GROUP_SUCCESS';
export const DELETE_USER_GROUP_SUCCESS = 'DELETE_USER_GROUP_SUCCESS';
export const GET_GROUP_FOR_USER_SUCCESS = 'GET_GROUP_FOR_USER_SUCCESS';
export const GET_PLAYERS = 'GET_PLAYERS';
export const GET_PLAYERS_SUCCESS = 'GET_PLAYERS_SUCCESS';
export const GET_PLAYERS_ERROR = 'GET_PLAYERS_ERROR';
export const SAVE_PLAYER_SUCCESS = 'SAVE_PLAYER_SUCCESS';
export const DELETE_PLAYER_SUCCESS = 'DELETE_PLAYER_SUCCESS';
export const GET_PLAYLIST_GROUPS = 'GET_PLAYLIST_GROUPS';
export const GET_PLAYLIST_GROUPS_SUCCESS = 'GET_PLAYLIST_GROUPS_SUCCESS';
export const GET_PLAYLIST_GROUPS_ERROR = 'GET_PLAYLIST_GROUPS_ERROR';
export const SAVE_PLAYLIST_GROUP_SUCCESS = 'SAVE_PLAYLIST_GROUP_SUCCESS';
export const DELETE_PLAYLIST_GROUP_SUCCESS = 'DELETE_PLAYLIST_GROUP_SUCCESS';
export const GET_SETTINGS_CATEGORIES = 'GET_SETTINGS_CATEGORIES';
export const GET_SETTINGS_CATEGORIES_SUCCESS = 'GET_SETTINGS_CATEGORIES_SUCCESS';
export const GET_SETTINGS_CATEGORIES_ERROR = 'GET_SETTINGS_CATEGORIES_ERROR';
export const SAVE_CATEGORY_SUCCESS = 'SAVE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const GET_PLAYER_TAG_TYPES = 'GET_PLAYER_TAG_TYPES';
export const GET_PLAYER_TAG_TYPES_SUCCESS = 'GET_PLAYER_TAG_TYPES_SUCCESS';
export const GET_PLAYER_TAG_TYPES_ERROR = 'GET_PLAYER_TAG_TYPES_ERROR';
export const SAVE_PLAYER_TAG_TYPE_SUCCESS = 'SAVE_PLAYER_TAG_TYPE_SUCCESS';
export const DELETE_PLAYER_TAG_TYPE_SUCCESS = 'DELETE_PLAYER_TAG_TYPE_SUCCESS';
export const GET_PLAYER_TAG_VALUES_SUCCESS = 'GET_PLAYER_TAG_VALUES_SUCCESS';
export const SAVE_PLAYER_TAG_VALUE_SUCCESS = 'SAVE_PLAYER_TAG_VALUE_SUCCESS';
export const DELETE_PLAYER_TAG_VALUE_SUCCESS = 'DELETE_PLAYER_TAG_VALUE_SUCCESS';
export const GET_GENERAL_SETTINGS = 'GET_GENERAL_SETTINGS';
export const GET_GENERAL_SETTINGS_SUCCESS = 'GET_GENERAL_SETTINGS_SUCCESS';
export const GET_GENERAL_SETTINGS_ERROR = 'GET_GENERAL_SETTINGS_ERROR';
export const SAVE_GENERAL_SETTINGS_SUCCESS = 'SAVE_GENERAL_SETTINGS_SUCCESS';
export const GET_MOBILE_USERS = 'GET_MOBILE_USERS';
export const GET_MOBILE_USERS_SUCCESS = 'GET_MOBILE_USERS_SUCCESS';
export const GET_MOBILE_USERS_ERROR = 'GET_MOBILE_USERS_ERROR';
export const SAVE_MOBILE_USER_SUCCESS = 'SAVE_MOBILE_USER_SUCCESS';
export const DELETE_MOBILE_USER_SUCCESS = 'DELETE_MOBILE_USER_SUCCESS';
export const GET_MOBILE_USER_JOBS = 'GET_MOBILE_USER_JOBS';
export const GET_MOBILE_USER_JOBS_SUCCESS = 'GET_MOBILE_USER_JOBS_SUCCESS';
export const GET_MOBILE_USER_JOBS_ERROR = 'GET_MOBILE_USER_JOBS_ERROR';
export const SAVE_MOBILE_USER_JOB_SUCCESS = 'SAVE_MOBILE_USER_JOB_SUCCESS';
export const DELETE_MOBILE_USER_JOB_SUCCESS = 'DELETE_MOBILE_USER_JOB_SUCCESS';
export const RETAG_MOBILE_USER_JOB_SUCCESS = 'RETAG_MOBILE_USER_JOB_SUCCESS';
export const GET_MOBILE_USER_DEPARTMENTS = 'GET_MOBILE_USER_DEPARTMENTS';
export const GET_MOBILE_USER_DEPARTMENTS_SUCCESS = 'GET_MOBILE_USER_DEPARTMENTS_SUCCESS';
export const GET_MOBILE_USER_DEPARTMENTS_ERROR = 'GET_MOBILE_USER_DEPARTMENTS_ERROR';
export const SAVE_MOBILE_USER_DEPARTMENT_SUCCESS = 'SAVE_MOBILE_USER_DEPARTMENT_SUCCESS';
export const DELETE_MOBILE_USER_DEPARTMENT_SUCCESS = 'DELETE_MOBILE_USER_DEPARTMENT_SUCCESS';
export const RETAG_MOBILE_USER_DEPARTMENT_SUCCESS = 'RETAG_MOBILE_USER_DEPARTMENT_SUCCESS';
export const GET_MOBILE_USER_COMPANIES = 'GET_MOBILE_USER_COMPANIES';
export const GET_MOBILE_USER_COMPANIES_SUCCESS = 'GET_MOBILE_USER_COMPANIES_SUCCESS';
export const GET_MOBILE_USER_COMPANIES_ERROR = 'GET_MOBILE_USER_COMPANIES_ERROR';
export const SAVE_MOBILE_USER_COMPANY_SUCCESS = 'SAVE_MOBILE_USER_COMPANY_SUCCESS';
export const DELETE_MOBILE_USER_COMPANY_SUCCESS = 'DELETE_MOBILE_USER_COMPANY_SUCCESS';
export const RETAG_MOBILE_USER_COMPANY_SUCCESS = 'RETAG_MOBILE_USER_COMPANY_SUCCESS';

// status changes
export const SLIDE_ACTIVE = 'active';
export const SLIDE_PLANNED = 'planned';
export const SLIDE_CONCEPT = 'concept';